language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
node_js:
- '5.4.1'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g bower@1.7.1 gulp@3.9.0
- bower i
env:
  global:
  - CXX='g++-4.8'
  - secure: SbcQ7plU7aRGQlaAG2ffMhSvEs84073YSljOQ62DZAjRxgizMhF4xM7H2mPrmac9YRM4IBrQRvBKMMZy3L6OhN8gwpm8o+w2zV+5Q1fwpY9V8bilznnhp1JUY6jrB2l7aLTOFxt/cG+5ABxiupwWz/n+I7BaByYhBiHWntIBgDc528eecRNDYI5R36KWjLO/yr+SdElvyxDlDOdJGaluPvgMItbinFGcE1hYb/Jqrkkw8zpE6CTDmvMOq1aRBWSo9afgh2zDeKc02lTYP/4N0xcn8CqzHF7k5zGWHjN9DR8Ep8Bp1ff/sM7zHGZBqgVhn5WGv305jBQY6eOxiTp5cDP0WVIOjgJeM5rBu9hBQxhZSaMKBPr2B1NYUjIwTVQkBsnR4sr095Ugjg8JCZAmEevf/Ysl4CzQyW3gT+WcEluqjxUuicQWDclH6L/kOVPBJ+Eqdo/LY3G1tpLcc6fsvj4FlVO6LPTrbMyCagwQvnjX3uIdFyuthqtWWrHKQMGx2Ow9suNUi8Hyvk7WboS1Z6jrLIcs1rvXSX8rQmlMR5vJBK3Ejg6fS1OHxn/lrtLhj4lDLB9r/Fcu2PEHT1lcvQqsTa3W+t4Fk1qaShUlBDiwMbZWZgmlf1SdG5OzK1yrPLjTTdRFdqJGgb6TANCdetgczRWynvjIhr5IDMxvfJg=
deploy:
  provider: s3
  access_key_id: AKIAISWBWHABLGP6QVCA
  secret_access_key:
    secure: LfXto887Cs9NiDu4RWLm7MBBwY9wMqieTAFXjLy2ln/OVCjze6Dc2vcT1KMt3VUTlg4lzHDswnI6u94OKlxEDOfaWCM5tlYmFqjQz2H0RUHu2if8zxMBYwXVGluBj3zC3KECTJ8ldojzmdigC9XI/WxsnjsiBBv62fL3oVpFEa1NN2qgXL8Yei126rrAbYn1j5bWcZ6AqstgFbbChTBoayy14L+xXqBud2qMBB38VDIf5GGksFthNrHmMLjsNLRvReSjTejvMbFVkS9vM7H85NaNpncXBrcLxjXKX66y/jE7T8iyLWbcPvcZRsq5/bNQWN7yVbjG9TvUf4Fukpy7GCsWYNxljlDVFBDQlnxBzqM+MnZ4Ocwvdp1yMN+J9La9ZjKMGW3RojvToGz/He6KYVeWM3o75G+THP/n4R5rb3D4L2UQZQOl3czeUJp9UpA0wKxGWmbBYbG9dtMqiwe/FW7oR1wKhek6WIwIlrH7Sk3kDAnnXyDRidVJ+tgaKo0Kogj1FDYgeyIJpEfTw4GzRn5ieuSSnKS5so/cWDKr8AL0SskjcUYJlNCOeyQwsQIQBmJ2OVFXKfvzgsH4zA+ZU1xh9tJ37sE89TWQVxhieWVq4YRFYD3oaGqS3u0gpf6bctcwgqnpTw4yQGblYBqDzah7TmfQc3HnkIvzpEqhKhw=
  bucket: carport
  acl: public_read
  on:
    repo: MackayDesigns/carport
  local_dir: build
